name: mobil
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  logger: ^2.0.2+1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/supplynexa.jpeg
    - images/anonim.jpeg
    - images/akü.jpeg
    - images/kaporta.jpg
    - images/radyo1.jpg
    - images/tekerlek.jpg
    - images/ayna.jpg

